title: SUN Cho Fei (Pascal)
description: Pascal's Personal Page
url: "https://sun-pascal.github.io"
baseurl: ""
repository: "sun-pascal/sun-pascal.github.io"

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default
search: false

markdown: kramdown
permalink: /:categories/:title/
timezone: Asia/Taipei

include:
  - _pages

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

author:
  name   : "SUN Cho Fei (Pascal)"
  avatar : "/assets/images/avatar.jpg"
  bio    : "MPhil in Statistics Â· CUHK"
  location: "Hong Kong"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:pascalsun@link.cuhk.edu.hk"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/pascalsun"


footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:pascalsun@link.cuhk.edu.hk"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/pascalsun"


defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

# Optional: keep this if you later add blog posts
# paginate: 5
# paginate_path: /page:num/
